apiVersion: v1
kind: Service
metadata:
  name: test-calculator
  labels:
    app: test-calculator
spec:
  selector:
    app: test-calculator
  ports:
  - port: 5000  
    protocol: TCP
    targetPort: 5000